### ISSUE TITLE
unable to connect service

### ISSUE THREAD

**Issue by littleningmeng** [CrusaderX/mongodb-charts#1]
netstat  -ant | grep 8080
tcp6       0      0 :::8080                 :::*                    LISTEN 

--  

docker images
REPOSITORY               TAG                 IMAGE ID            CREATED             SIZE
charts                   latest              c4c6b1400cdb        2 minutes ago       744MB
charts_mongo             latest              9284b30f2f86        2 minutes ago       447MB
mongo                    3.6                 eaff3e31881d        11 days ago         447MB
quay.io/mongodb/charts   19.12.1             7ea5a2d02af2        13 months ago       728MB

--  

telnet localhost 8080
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Connection closed by foreign host.

**Comment by CrusaderX** [comment]
You got `Connection closed by foreign host.` - can you check that's there is no any other listeners with this port? What is the output of the command `curl localhost:8080`? And please wrap code with markdown style for readability.

**Comment by littleningmeng** [comment]
> You got `Connection closed by foreign host.` - can you check that's there is no any other listeners with this port? What is the output of the command `curl localhost:8080`? And please wrap code with markdown style for readability.

Yes，you are right
It's my fault
